# Generated by Django 5.1.3 on 2024-11-25 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compra', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_usuario', to='carro_compra.usuario'),
        ),
    ]
